### ISSUE TITLE
async.operations.all retries

### ISSUE THREAD

**Issue by VincentBean** [run-as-root/magento2-message-queue-retry#32]
We are attempting to add retries the the `async.operations.all` queue in Magento to retry messages sent through the async rest API.

Would it be possible to get a bit of guidance on how to set this up?

In the configuration example you use a `erp_order_export` queue, I am trying to find the equivalent for the async operations but can only find this in `vendor/magento/module-webapi-async/etc/queue_topology.xml`

```xml
    <exchange name="magento">
        <binding id="async.operations.all" topic="async.#" destination="async.operations.all"/>
    </exchange>
```

Is it even possible to do this or do we need to configure each of the underlaying topics such as the two configured in `vendor/magento/module-catalog/etc/communication.xml`?

I am testing this by throwing an exception in the `ProductRepository`, I am seeing the result in the `magento_operation` table, I do notice that it does not reach the reject function in `vendor/magento/framework-amqp/Queue.php` and the status in the table stays `3` which is processing I assume (if the status matches `vendor/magento/module-mysql-mq/Model/QueueManagement.php`)

This is also probably not an issue with the library but just configuration, we are looking for a push in the right direction of setting this up.

**Comment by cristiano-pacheco** [comment]
Hello @VincentBean,

It is not possible to configure a dead letter exchange  to the `magento` exchange because it is linked with multiple topics/queues.

Please look [here](https://github.com/run-as-root/magento2-message-queue-retry/blob/develop/docs/queue-requirement.png).

That is, we simulate a `direct` exchange type as Magento only supports `topic` exchange type.
